/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myapp.view.staff;

import myapp.util.commonTask.CommonTask;
import myapp.view.LoginView;

/**
 *
 * @author HP
 */
public class AdminDashboardView extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanelView
     * @param userName
    */
    
    private final String userName;
    
    public AdminDashboardView(String userName) {
        initComponents();
        
        this.userName = userName;
        lbl_copyright.setText("@Dannoruwa-Anush 2025");
        lbl_loggedUser.setText("( " + this.userName + " )");
        lbl_logout.setText("<html><u>(Logout)</u></html>");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle1 = new javax.swing.JLabel();
        lbl_loggedUser = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lbl_copyright = new javax.swing.JLabel();
        btn_createWeeklySchedule = new javax.swing.JButton();
        btn_routeInfo = new javax.swing.JButton();
        btn_airportInfo = new javax.swing.JButton();
        btn_aircaraftInfo = new javax.swing.JButton();
        btn_passengerProfileInfo = new javax.swing.JButton();
        btn_bookingInfo = new javax.swing.JButton();
        btn_flightClassPricingInfo = new javax.swing.JButton();
        btn_bookingClassInfo = new javax.swing.JButton();
        btn_userRoleInfo = new javax.swing.JButton();
        btn_flightSheduleInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle1.setBackground(new java.awt.Color(204, 204, 204));
        lblTitle1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Admin Dashboard");

        lbl_loggedUser.setForeground(new java.awt.Color(0, 51, 255));
        lbl_loggedUser.setText("(username)");

        lbl_logout.setForeground(new java.awt.Color(0, 51, 255));
        lbl_logout.setText("(logout)");
        lbl_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });

        jLabel2.setText("Airline Ticket Booking System");

        lbl_copyright.setText("@C");

        btn_createWeeklySchedule.setText("Weekly Schedule");
        btn_createWeeklySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createWeeklyScheduleActionPerformed(evt);
            }
        });

        btn_routeInfo.setText("Route Info");
        btn_routeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_routeInfoActionPerformed(evt);
            }
        });

        btn_airportInfo.setText("Airport Info");
        btn_airportInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_airportInfoActionPerformed(evt);
            }
        });

        btn_aircaraftInfo.setText("Aircraft Info");
        btn_aircaraftInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aircaraftInfoActionPerformed(evt);
            }
        });

        btn_passengerProfileInfo.setText("Passenger Info");
        btn_passengerProfileInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_passengerProfileInfoActionPerformed(evt);
            }
        });

        btn_bookingInfo.setText("Booking Info");
        btn_bookingInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookingInfoActionPerformed(evt);
            }
        });

        btn_flightClassPricingInfo.setText("Flight Class Pricing Info");
        btn_flightClassPricingInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_flightClassPricingInfoActionPerformed(evt);
            }
        });

        btn_bookingClassInfo.setText("Booking Class Info");
        btn_bookingClassInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookingClassInfoActionPerformed(evt);
            }
        });

        btn_userRoleInfo.setText("User Role Info");
        btn_userRoleInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userRoleInfoActionPerformed(evt);
            }
        });

        btn_flightSheduleInfo.setText("Flight Shedule Info");
        btn_flightSheduleInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_flightSheduleInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_loggedUser)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_passengerProfileInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_userRoleInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_airportInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_aircaraftInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_routeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_flightSheduleInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btn_createWeeklySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_flightClassPricingInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_bookingInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_bookingClassInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_copyright)))
                .addGap(270, 270, 270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_logout)
                    .addComponent(lbl_loggedUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_userRoleInfo)
                    .addComponent(btn_airportInfo)
                    .addComponent(btn_aircaraftInfo)
                    .addComponent(btn_bookingClassInfo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_routeInfo)
                    .addComponent(btn_flightClassPricingInfo)
                    .addComponent(btn_flightSheduleInfo)
                    .addComponent(btn_passengerProfileInfo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_bookingInfo)
                    .addComponent(btn_createWeeklySchedule))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_copyright)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bookingInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookingInfoActionPerformed
        CommonTask.switchView(this, new ReservationStaffView(this.userName));
    }//GEN-LAST:event_btn_bookingInfoActionPerformed

    private void btn_userRoleInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userRoleInfoActionPerformed
        CommonTask.switchView(this, new UserRoleView(this.userName));
    }//GEN-LAST:event_btn_userRoleInfoActionPerformed

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        CommonTask.switchView(this, new LoginView());
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void btn_airportInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_airportInfoActionPerformed
        CommonTask.switchView(this, new AirportView(this.userName));
    }//GEN-LAST:event_btn_airportInfoActionPerformed

    private void btn_routeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_routeInfoActionPerformed
        CommonTask.switchView(this, new RouteView(this.userName));
    }//GEN-LAST:event_btn_routeInfoActionPerformed

    private void btn_aircaraftInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aircaraftInfoActionPerformed
        CommonTask.switchView(this, new AirCraftModelView(this.userName));
    }//GEN-LAST:event_btn_aircaraftInfoActionPerformed

    private void btn_createWeeklyScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createWeeklyScheduleActionPerformed
        CommonTask.switchView(this, new FlightView(this.userName));
    }//GEN-LAST:event_btn_createWeeklyScheduleActionPerformed

    private void btn_bookingClassInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookingClassInfoActionPerformed
        CommonTask.switchView(this, new BookingClassView(this.userName));
    }//GEN-LAST:event_btn_bookingClassInfoActionPerformed

    private void btn_flightClassPricingInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_flightClassPricingInfoActionPerformed
        CommonTask.switchView(this, new FlightClassPriceView(this.userName));
    }//GEN-LAST:event_btn_flightClassPricingInfoActionPerformed

    private void btn_passengerProfileInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_passengerProfileInfoActionPerformed
        CommonTask.switchView(this, new PassengerProfileStaffView(this.userName));
    }//GEN-LAST:event_btn_passengerProfileInfoActionPerformed

    private void btn_flightSheduleInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_flightSheduleInfoActionPerformed
        CommonTask.switchView(this, new FlightScheduleView(this.userName));
    }//GEN-LAST:event_btn_flightSheduleInfoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminDashboardView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aircaraftInfo;
    private javax.swing.JButton btn_airportInfo;
    private javax.swing.JButton btn_bookingClassInfo;
    private javax.swing.JButton btn_bookingInfo;
    private javax.swing.JButton btn_createWeeklySchedule;
    private javax.swing.JButton btn_flightClassPricingInfo;
    private javax.swing.JButton btn_flightSheduleInfo;
    private javax.swing.JButton btn_passengerProfileInfo;
    private javax.swing.JButton btn_routeInfo;
    private javax.swing.JButton btn_userRoleInfo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lbl_copyright;
    private javax.swing.JLabel lbl_loggedUser;
    private javax.swing.JLabel lbl_logout;
    // End of variables declaration//GEN-END:variables
}
