/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myapp.view.user;

import java.awt.Cursor;
import myapp.controller.PassengerProfileController;
import myapp.dto.passengerProfile.PassengerProfileResponseDTO;
import myapp.dto.reservation.ReservationTabInteractionDTO;
import myapp.util.audit.AuditUtil;
import myapp.util.commonTask.CommonTask;
import myapp.util.commonUI.CommonMessageBoxUI;
import myapp.util.enums.UserDashBoardViewTypeEnum;
import myapp.view.LoginView;

/**
 *
 * @author HP
 */
public class UserDashboardView extends javax.swing.JFrame {

    /**
     * Creates new form UserDashboardView
     */
    private final String userName;
    private ReservationTabInteractionDTO reservationTabInteractionDTO;
    private final int userId;

    private final PassengerProfileController passengerProfileController;

    public UserDashboardView(String userName, int userId) {
        initComponents();

        this.userName = userName;
        this.userId = userId;

        this.reservationTabInteractionDTO = new ReservationTabInteractionDTO();
        passengerProfileController = new PassengerProfileController();
        
        initializeUIState();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle1 = new javax.swing.JLabel();
        lbl_logout = new javax.swing.JLabel();
        lbl_loggedUser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_bookingInfo = new javax.swing.JButton();
        btn_profileInfo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lbl_copyright = new javax.swing.JLabel();
        btn_flightInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle1.setBackground(new java.awt.Color(204, 204, 204));
        lblTitle1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("User Dashboard");

        lbl_logout.setForeground(new java.awt.Color(0, 51, 255));
        lbl_logout.setText("(logout)");
        lbl_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });

        lbl_loggedUser.setForeground(new java.awt.Color(0, 51, 255));
        lbl_loggedUser.setText("(username)");

        btn_bookingInfo.setText("Booking Info");
        btn_bookingInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookingInfoActionPerformed(evt);
            }
        });

        btn_profileInfo.setText("Profile Info");
        btn_profileInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profileInfoActionPerformed(evt);
            }
        });

        jLabel2.setText("Airline Ticket Booking System");

        lbl_copyright.setText("@C");

        btn_flightInfo.setText("Flight Info");
        btn_flightInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_flightInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_flightInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_bookingInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_profileInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_copyright)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_loggedUser)
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_logout)
                    .addComponent(lbl_loggedUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_profileInfo)
                .addGap(18, 18, 18)
                .addComponent(btn_bookingInfo)
                .addGap(18, 18, 18)
                .addComponent(btn_flightInfo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_copyright)
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        CommonTask.switchView(this, new LoginView());
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void btn_bookingInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookingInfoActionPerformed
        userDashboardBtnOptionHandler(userId, UserDashBoardViewTypeEnum.BOOKING_INFO);
    }//GEN-LAST:event_btn_bookingInfoActionPerformed

    private void btn_profileInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileInfoActionPerformed
        userDashboardBtnOptionHandler(userId, UserDashBoardViewTypeEnum.PROFILE_INFO);
    }//GEN-LAST:event_btn_profileInfoActionPerformed

    private void btn_flightInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_flightInfoActionPerformed
        userDashboardBtnOptionHandler(userId, UserDashBoardViewTypeEnum.FLIGHT_INFo);
    }//GEN-LAST:event_btn_flightInfoActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserDashboardView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bookingInfo;
    private javax.swing.JButton btn_flightInfo;
    private javax.swing.JButton btn_profileInfo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lbl_copyright;
    private javax.swing.JLabel lbl_loggedUser;
    private javax.swing.JLabel lbl_logout;
    // End of variables declaration//GEN-END:variables

    //-------- [ Start - btn handle ] --------------------------
    private void initCommonLabels() {
        lbl_loggedUser.setText("( " + this.userName + " )");
        lbl_logout.setText("<html><u>(Logout)</u></html>");
        lbl_logout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lbl_copyright.setText("@Dannoruwa-Anush 2025");
    }
        
    private void userDashboardBtnOptionHandler(int userId, UserDashBoardViewTypeEnum targetView) {
        try {
            PassengerProfileResponseDTO passengerProfile = getPassengerProfileInfo(userId);

            if (passengerProfile == null) {
                boolean confirmed = CommonMessageBoxUI.showOkCancelConfirmationMessageBox(
                        this,
                        "Before proceeding forward you need to create a passenger profile.",
                        "Profile Required"
                );

                if (confirmed) {
                    CommonTask.switchView(this, new PassengerProfileUserView(this.userName, this.userId, passengerProfile));
                }
                return;
            }

            switch (targetView) {
                case BOOKING_INFO-> CommonTask.switchView(this, new ReservationUserView(this.userName, this.userId, passengerProfile.getPassengerId()));
                case PROFILE_INFO -> CommonTask.switchView(this, new PassengerProfileUserView(this.userName, this.userId, passengerProfile));
                default -> {
                    if (this.reservationTabInteractionDTO != null) {
                        //add passenger_id to the request obj
                        this.reservationTabInteractionDTO.setPassengerId(passengerProfile.getPassengerId());
                    }
                    CommonTask.switchView(this, new ReservationFlightTabView(this.userName, this.userId, this.reservationTabInteractionDTO));
                }

            }

        } catch (Exception ex) {
            AuditUtil.logException(this.getClass(), ex);
        }
    }

    private PassengerProfileResponseDTO getPassengerProfileInfo(int userId) throws Exception {
        return passengerProfileController.getPassengerProfileByUserId(userId);
    }

    //****** [Start : Reset] ***************
    private void initializeUIState() {
        initCommonLabels();
    }
    //****** [End : Reset] ***************
    //-------- [ End - btn handle ] ----------------------------
}
